const DEFAULT_VERBS = [
  // === TOPIC 1: ЕМОЦІЇ ТА ПОЧУТТЯ ===
  {
    id: 'i1',
    verb: 'on cloud nine',
    translation: 'на сьомому небі від щастя',
    topicId: 't1',
    status: 'new',
    example: 'She was on cloud nine when she heard the good news.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i2',
    verb: 'under the weather',
    translation: 'погано себе почувати, прихворіти',
    topicId: 't1',
    status: 'new',
    example: 'I am feeling a bit under the weather today.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i3',
    verb: 'over the moon',
    translation: 'неймовірно щасливий',
    topicId: 't1',
    status: 'new',
    example: 'They were over the moon about their engagement.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i4',
    verb: 'down in the dumps',
    translation: 'як у воду опущений, сумувати',
    topicId: 't1',
    status: 'new',
    example: 'He’s been down in the dumps since he failed his test.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i5',
    verb: "make one's blood boil",
    translation: 'злити когось до сказу, змушувати кров кипіти',
    topicId: 't1',
    status: 'new',
    example: 'His rude behavior makes my blood boil.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i6',
    verb: "bite one's head off",
    translation: 'накинутися на когось із криком, огризнутися',
    topicId: 't1',
    status: 'new',
    example: 'I only asked a question, don’t bite my head off!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i7',
    verb: 'face like a wet weekend',
    translation: 'дуже сумне, понуре обличчя',
    topicId: 't1',
    status: 'new',
    example: 'Why do you have a face like a wet weekend?',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i8',
    verb: 'on pins and needles',
    translation: 'як на голках, сильно нервувати',
    topicId: 't1',
    status: 'new',
    example: 'We were on pins and needles waiting for the results.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i9',
    verb: "have butterflies in one's stomach",
    translation: 'нервувати перед виступом чи через закоханість',
    topicId: 't1',
    status: 'new',
    example: 'I had butterflies in my stomach before the interview.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i10',
    verb: "cry one's eyes out",
    translation: 'гірко плакати, виплакати всі очі',
    topicId: 't1',
    status: 'new',
    example: 'She cried her eyes out after reading the letter.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i11',
    verb: "keep one's chin up",
    translation: 'не падати духом, тримати хвіст пістолетом',
    topicId: 't1',
    status: 'new',
    example: 'Keep your chin up, things will get better soon.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i12',
    verb: 'out of sorts',
    translation: 'не в гуморі, трохи прихворілий',
    topicId: 't1',
    status: 'new',
    example: 'The baby is out of sorts because he is teething.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i13',
    verb: 'scared to death',
    translation: 'наляканий до смерті',
    topicId: 't1',
    status: 'new',
    example: 'I was scared to death when the lights suddenly went out.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i14',
    verb: 'bored to tears',
    translation: 'знуджений до сліз',
    topicId: 't1',
    status: 'new',
    example: 'I was bored to tears during that long lecture.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i15',
    verb: 'beside oneself',
    translation: 'бути поза собою від горя чи радості',
    topicId: 't1',
    status: 'new',
    example: 'She was beside herself with grief after losing her pet.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i16',
    verb: 'green with envy',
    translation: 'зеленіти від заздрощів',
    topicId: 't1',
    status: 'new',
    example: 'She was green with envy when she saw my new car.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i17',
    verb: 'no hard feelings',
    translation: 'без образ, без зла',
    topicId: 't1',
    status: 'new',
    example: 'We argued, but there are no hard feelings between us.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i18',
    verb: "at the end of one's tether",
    translation: 'на межі терпіння, сили вичерпалися',
    topicId: 't1',
    status: 'new',
    example:
      'I’ve been dealing with this noise for hours and I’m at the end of my tether.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i19',
    verb: 'fly off the handle',
    translation: 'раптово вийти з себе, розізлитися',
    topicId: 't1',
    status: 'new',
    example: 'He tends to fly off the handle when things go wrong.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i20',
    verb: 'tickled pink',
    translation: 'дуже задоволений, радісний',
    topicId: 't1',
    status: 'new',
    example: 'He was tickled pink with his birthday present.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i21',
    verb: 'heavy heart',
    translation: 'з важким серцем, з сумом',
    topicId: 't1',
    status: 'new',
    example: 'With a heavy heart, she packed her bags to leave.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i22',
    verb: 'worry oneself sick',
    translation: 'захворіти від хвилювання',
    topicId: 't1',
    status: 'new',
    example: 'His mother worried herself sick when he didn’t call.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i23',
    verb: 'proud as a peacock',
    translation: 'гордий як павич',
    topicId: 't1',
    status: 'new',
    example: 'He was proud as a peacock when he won first prize.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i24',
    verb: 'burst with joy',
    translation: 'розриватися від радості',
    topicId: 't1',
    status: 'new',
    example: 'They were bursting with joy at the baby news.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i25',
    verb: 'in high spirits',
    translation: 'у піднесеному настрої',
    topicId: 't1',
    status: 'new',
    example: 'Everyone was in high spirits at the holiday dinner.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i26',
    verb: 'add insult to injury',
    translation: 'сипати сіль на рану, погіршувати ситуацію',
    topicId: 't1',
    status: 'new',
    example:
      'To add insult to injury, it started to rain when we got flat tire.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i27',
    verb: 'feel like a million dollars',
    translation: 'почуватися чудово, виглядати на всі сто',
    topicId: 't1',
    status: 'new',
    example: 'After a good sleep, she felt like a million dollars.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i28',
    verb: "lose one's cool",
    translation: 'втратити самовладання, зірватися',
    topicId: 't1',
    status: 'new',
    example: 'Try to stay calm and don’t lose your cool.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i29',
    verb: 'safe and sound',
    translation: 'цілий та неушкоджений',
    topicId: 't1',
    status: 'new',
    example: 'They arrived home safe and sound after the storm.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i30',
    verb: "keep one's temper",
    translation: 'стримувати свій гнів, тримати себе в руках',
    topicId: 't1',
    status: 'new',
    example: 'It was hard to keep my temper during that discussion.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i31',
    verb: 'all ears',
    translation: 'перетворитися на слух, уважно слухати',
    topicId: 't1',
    status: 'new',
    example: 'Tell me what happened, I am all ears.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i32',
    verb: 'bear a grudge',
    translation: 'мати зуб на когось, тримати образу',
    topicId: 't1',
    status: 'new',
    example: 'He still bears a grudge after we argued last year.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i33',
    verb: "on the edge of one's seat",
    translation: 'з нетерпінням очікувати розвитку подій',
    topicId: 't1',
    status: 'new',
    example: 'The movie’s ending kept me on the edge of my seat.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i34',
    verb: 'hit the roof',
    translation: 'розізлитися вкрай, стрибати від люті',
    topicId: 't1',
    status: 'new',
    example: 'My dad hit the roof when he saw the broken window.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i35',
    verb: 'gloom and doom',
    translation: 'морок і песимізм, безнадія',
    topicId: 't1',
    status: 'new',
    example: 'Stop spreading gloom and doom, we will find a solution.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i36',
    verb: 'feel blue',
    translation: 'сумувати, нудьгувати',
    topicId: 't1',
    status: 'new',
    example: 'I always feel blue on rainy Sundays.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i37',
    verb: 'have a soft spot for',
    translation: 'мати слабкість до когось/чогось, дуже любити',
    topicId: 't1',
    status: 'new',
    example: 'She has a soft spot for stray cats.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i38',
    verb: 'with mixed feelings',
    translation: 'зі змішаними почуттями',
    topicId: 't1',
    status: 'new',
    example:
      'I received the promotion with mixed feelings because I have to move.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i39',
    verb: 'breathe easily',
    translation: 'зітхнути з полегшенням',
    topicId: 't1',
    status: 'new',
    example: 'Now that the exams are over, I can breathe easily.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i40',
    verb: 'not sleep a wink',
    translation: 'і оком не змигнути',
    topicId: 't1',
    status: 'new',
    example: 'I didn’t sleep a wink last night because of the noise.',
    lastReviewed: null,
    repetitions: 0,
  },

  // === TOPIC 2: РОБОТА, УСПІХ ТА ТРУДНОЩІ ===
  {
    id: 'i41',
    verb: 'bite the bullet',
    translation: 'зціпити зуби, мужньо прийняти неминуче',
    topicId: 't2',
    status: 'new',
    example: 'I have to bite the bullet and tell him the truth.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i42',
    verb: 'burn the midnight oil',
    translation: 'працювати допізна, вчитися ночами',
    topicId: 't2',
    status: 'new',
    example: 'She had to burn the midnight oil to prepare for her exam.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i43',
    verb: 'cut corners',
    translation: 'халтурити, йти найпростішим шляхом на шкоду якості',
    topicId: 't2',
    status: 'new',
    example: 'Never cut corners when it comes to construction safety.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i44',
    verb: 'call it a day',
    translation: 'закінчити роботу на сьогодні, розійтися',
    topicId: 't2',
    status: 'new',
    example: 'We are all tired, let’s call it a day.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i45',
    verb: 'back to the drawing board',
    translation: 'почати все з чистого аркуша через невдачу',
    topicId: 't2',
    status: 'new',
    example: 'Our proposal was rejected, so it’s back to the drawing board.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i46',
    verb: 'hit the nail on the head',
    translation: 'влучити в самісіньку ціль, сказати прямо в точку',
    topicId: 't2',
    status: 'new',
    example: 'Your analysis of the problem really hit the nail on the head.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i47',
    verb: 'get the sack',
    translation: 'бути звільненим з роботи',
    topicId: 't2',
    status: 'new',
    example: 'He got the sack because he was always late.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i48',
    verb: 'go the extra mile',
    translation: 'зробити більше, ніж від тебе вимагається',
    topicId: 't2',
    status: 'new',
    example: 'He always goes the extra mile to make his clients happy.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i49',
    verb: "keep one's head above water",
    translation: 'ледве триматися на плаву (фінансово чи в роботі)',
    topicId: 't2',
    status: 'new',
    example: 'With rising rents, it’s hard to keep our head above water.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i50',
    verb: 'think outside the box',
    translation: 'мислити нестандартно, креативно',
    topicId: 't2',
    status: 'new',
    example: 'To solve this problem, we need to think outside the box.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i51',
    verb: 'pull oneself together',
    translation: 'взяти себе в руки, зібратися з силами',
    topicId: 't2',
    status: 'new',
    example: 'Stop crying and pull yourself together!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i52',
    verb: 'work fingers to the bone',
    translation: 'тяжко працювати, не покладаючи рук',
    topicId: 't2',
    status: 'new',
    example: 'She worked her fingers to the bone to support her family.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i53',
    verb: 'learn the ropes',
    translation: 'освоїти ази справи, увійти в курс справ',
    topicId: 't2',
    status: 'new',
    example: 'It takes a few weeks for a new employee to learn the ropes.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i54',
    verb: "by the skin of one's teeth",
    translation: 'ледве-ледве, дивом уникнути поразки/проблем',
    topicId: 't2',
    status: 'new',
    example: 'I passed the exam by the skin of my teeth.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i55',
    verb: 'in the same boat',
    translation: 'в однакових умовах, в одному човні',
    topicId: 't2',
    status: 'new',
    example: 'Don’t complain, we are all in the same boat here.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i56',
    verb: 'hit the ground running',
    translation: 'відразу взятися до справи без зволікань',
    topicId: 't2',
    status: 'new',
    example: 'We need someone who can hit the ground running from day one.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i57',
    verb: 'show someone the door',
    translation: 'вказати комусь на двері, виставити',
    topicId: 't2',
    status: 'new',
    example: 'If he behaves badly, show him the door.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i58',
    verb: 'bring home the bacon',
    translation: 'заробляти гроші на сім’ю, забезпечувати родину',
    topicId: 't2',
    status: 'new',
    example: 'My wife stays home with the kids and I bring home the bacon.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i59',
    verb: 'slack off',
    translation: 'лінтяювати, працювати абияк',
    topicId: 't2',
    status: 'new',
    example: 'Don’t slack off now, we are almost done with the project.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i60',
    verb: 'the sky is the limit',
    translation: 'немає ніяких меж для розвитку',
    topicId: 't2',
    status: 'new',
    example: 'If you work hard in this company, the sky is the limit.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i61',
    verb: 'put something on hold',
    translation: 'відклати справу на потім, заморозити',
    topicId: 't2',
    status: 'new',
    example: 'We have to put the new project on hold due to budget cuts.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i62',
    verb: 'gain ground',
    translation: 'просуватися вперед, ставати популярнішим',
    topicId: 't2',
    status: 'new',
    example: 'Our new product is slowly gaining ground in the market.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i63',
    verb: 'raise the bar',
    translation: 'підняти планку, висунути вищі вимоги',
    topicId: 't2',
    status: 'new',
    example: 'Her performance raised the bar for everyone in the class.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i64',
    verb: 'climb the career ladder',
    translation: 'рухатися по кар’єрних сходах',
    topicId: 't2',
    status: 'new',
    example: 'He worked hard for ten years to climb the career ladder.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i65',
    verb: 'pass with flying colors',
    translation: 'успішно та з блиском скласти іспит',
    topicId: 't2',
    status: 'new',
    example: 'She passed her driving test with flying colors.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i66',
    verb: 'leave no stone unturned',
    translation: 'зробити все можливе, перевернути небо і землю',
    topicId: 't2',
    status: 'new',
    example: 'The detective left no stone unturned in finding the truth.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i67',
    verb: 'skate on thin ice',
    translation: 'ходити по тонкому льоду, ризикувати',
    topicId: 't2',
    status: 'new',
    example: 'If you miss another deadline, you’ll be skating on thin ice.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i68',
    verb: 'make a long story short',
    translation: 'коротше кажучи',
    topicId: 't2',
    status: 'new',
    example: 'To make a long story short, we got lost and missed the plane.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i69',
    verb: "have too much on one's plate",
    translation: 'мати занадто багато справ та обов’язків',
    topicId: 't2',
    status: 'new',
    example: 'I can’t help you today, I have too much on my plate.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i70',
    verb: 'touch and go',
    translation: 'ризикована, непевна ситуація',
    topicId: 't2',
    status: 'new',
    example: 'It was touch and go for a while, but the surgery was successful.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i71',
    verb: 'face the music',
    translation: 'мужньо зустріти критику, розплачуватися за вчинки',
    topicId: 't2',
    status: 'new',
    example: 'You broke the window, now you have to face the music.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i72',
    verb: 'miss the boat',
    translation: 'втратити гарну можливість, запізнитися',
    topicId: 't2',
    status: 'new',
    example: 'Apply today or you might miss the boat on this job offer.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i73',
    verb: "keep one's fingers crossed",
    translation: 'тримати кулаки за успіх',
    topicId: 't2',
    status: 'new',
    example:
      'I have my interview tomorrow, so keep your fingers crossed for me.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i74',
    verb: 'get down to business',
    translation: 'перейти до справи, до головного',
    topicId: 't2',
    status: 'new',
    example: 'Let’s stop chatting and get down to business.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i75',
    verb: "stand one's ground",
    translation: 'відстоювати свою позицію, стоять на своєму',
    topicId: 't2',
    status: 'new',
    example: 'Despite the pressure, she stood her ground on the decision.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i76',
    verb: 'up in the air',
    translation: 'під питанням, ще не вирішено',
    topicId: 't2',
    status: 'new',
    example: 'Our travel plans are still up in the air due to the strike.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i77',
    verb: "blow one's own trumpet",
    translation: 'вихвалятися своїми досягненнями',
    topicId: 't2',
    status: 'new',
    example: 'I don’t want to blow my own trumpet, but I did a great job.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i78',
    verb: 'play second fiddle',
    translation: 'бути на других ролях, грати другу скрипку',
    topicId: 't2',
    status: 'new',
    example: 'I tired of playing second fiddle to my business partner.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i79',
    verb: 'take the bull by the horns',
    translation: 'взяти бика за роги, рішуче діяти',
    topicId: 't2',
    status: 'new',
    example: 'She decided to take the bull by the horns and ask for a raise.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i80',
    verb: 'burn bridges',
    translation: 'спалювати мости',
    topicId: 't2',
    status: 'new',
    example: 'Even if you quit this job, don’t burn your bridges.',
    lastReviewed: null,
    repetitions: 0,
  },

  // === TOPIC 3: СПІЛКУВАННЯ ТА СТОСУНКИ ===
  {
    id: 'i81',
    verb: 'break the ice',
    translation: 'розтопити лід, розрядити атмосферу',
    topicId: 't3',
    status: 'new',
    example: 'He told a joke to break the ice at the party.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i82',
    verb: 'spill the beans',
    translation: 'пробовкатися, розкрити секрет завчасно',
    topicId: 't3',
    status: 'new',
    example: 'We wanted it to be a surprise, but he spilled the beans.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i83',
    verb: 'beat around the bush',
    translation: 'ходити довкола, уникати прямої відповіді',
    topicId: 't3',
    status: 'new',
    example: 'Stop beating around the bush and tell me what you want.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i84',
    verb: 'keep in touch',
    translation: 'підтримувати зв’язок, спілкуватися',
    topicId: 't3',
    status: 'new',
    example: 'Let’s keep in touch after you move to another country.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i85',
    verb: 'get on like a house on fire',
    translation: 'швидко здружитися, жити душа в душу',
    topicId: 't3',
    status: 'new',
    example: 'The kids met yesterday and got on like a house on fire.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i86',
    verb: 'speak of the devil',
    translation: 'про вовка промовка (коли з’являється об’єкт розмови)',
    topicId: 't3',
    status: 'new',
    example: 'Speak of the devil! Here comes Mark now.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i87',
    verb: 'hear on the grapevine',
    translation: 'почути краєм вуха, дізнатися за чутками',
    topicId: 't3',
    status: 'new',
    example: 'I heard on the grapevine that they are getting married.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i88',
    verb: 'give someone the cold shoulder',
    translation: 'ігнорувати когось, демонструвати байдужість',
    topicId: 't3',
    status: 'new',
    example: 'Since our argument, she has been giving me the cold shoulder.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i89',
    verb: "put one's foot in it",
    translation: 'бовкнути дурницю, вляпатися в незручну ситуацію',
    topicId: 't3',
    status: 'new',
    example: 'I really put my foot in it when I asked about his ex-wife.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i90',
    verb: 'see eye to eye',
    translation: 'погоджуватися в поглядах, сходитися характерами',
    topicId: 't3',
    status: 'new',
    example: 'My sister and I don’t always see eye to eye on politics.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i91',
    verb: 'be on the same wavelength',
    translation: 'бути на одній хвилі, розуміти без слів',
    topicId: 't3',
    status: 'new',
    example: 'We get along great because we are on the same wavelength.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i92',
    verb: 'get the wrong end of the stick',
    translation: 'неправильно щось зрозуміти, перекрутити',
    topicId: 't3',
    status: 'new',
    example: 'You got the wrong end of the stick, I was just trying to help.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i93',
    verb: 'keep someone in the dark',
    translation: 'тримати когось в невіданні, приховувати щось',
    topicId: 't3',
    status: 'new',
    example: 'They kept me in the dark about their financial problems.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i94',
    verb: 'take something with a pinch of salt',
    translation: 'ставитися скептично до інформації, ділити навпіл',
    topicId: 't3',
    status: 'new',
    example: 'You should take his stories with a pinch of salt.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i95',
    verb: 'get a word in edgeways',
    translation: 'вставити хоч слово під час чужої балаканини',
    topicId: 't3',
    status: 'new',
    example: 'She talked so much I couldn’t get a word in edgeways.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i96',
    verb: "talk behind someone's back",
    translation: 'говорити за чиєюсь спиною, обговорювати',
    topicId: 't3',
    status: 'new',
    example: 'If you have a problem with me, don’t talk behind my back.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i97',
    verb: 'clear the air',
    translation: 'розрядити напружену атмосферу, відверто поговорити',
    topicId: 't3',
    status: 'new',
    example: 'We need an honest conversation to clear the air.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i98',
    verb: "bite one's tongue",
    translation: 'прикусити язика, стриматися від коментаря',
    topicId: 't3',
    status: 'new',
    example: 'I wanted to argue, but I bit my tongue instead.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i99',
    verb: 'behind closed doors',
    translation: 'за зачиненими дверима, таємно',
    topicId: 't3',
    status: 'new',
    example: 'The decision was made behind closed doors by the directors.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i100',
    verb: 'stab in the back',
    translation: 'вдарити ножем у спину, зрадити',
    topicId: 't3',
    status: 'new',
    example: 'I trusted him, and he stabbed me in the back.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i101',
    verb: 'make peace with',
    translation: 'помиритися з кимось',
    topicId: 't3',
    status: 'new',
    example: 'It’s time to make peace with your neighbors.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i102',
    verb: 'lose touch',
    translation: 'втратити зв’язок через час чи відстань',
    topicId: 't3',
    status: 'new',
    example: 'We were friends in school, but we lost touch.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i103',
    verb: 'build bridges',
    translation: 'налагоджувати стосунки, будувати мости',
    topicId: 't3',
    status: 'new',
    example:
      'The diplomats are working hard to build bridges between the nations.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i104',
    verb: 'ring a bell',
    translation: 'звучати знайомо, нагадувати щось',
    topicId: 't3',
    status: 'new',
    example: 'His name rings a bell, but I don’t remember his face.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i105',
    verb: 'lead someone up the garden path',
    translation: 'водити за ніс, свідомо вводити в оману',
    topicId: 't3',
    status: 'new',
    example: 'Don’t believe him, he is leading you up the garden path.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i106',
    verb: 'keep a straight face',
    translation: 'стримувати сміх, зберігати серйозний вигляд',
    topicId: 't3',
    status: 'new',
    example: 'It was so funny, I could hardly keep a straight face.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i107',
    verb: 'read between the lines',
    translation: 'читати між рядків',
    topicId: 't3',
    status: 'new',
    example:
      'Reading between the lines, she isn’t very happy with her new position.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i108',
    verb: 'lay cards on the table',
    translation: 'розкрити всі карти, вести відкриту гру',
    topicId: 't3',
    status: 'new',
    example: 'Let’s lay our cards on the table and negotiate fairly.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i109',
    verb: "wash one's hands of",
    translation: 'умити руки, зняти з себе відповідальність',
    topicId: 't3',
    status: 'new',
    example: 'I am washing my hands of this project, do what you want.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i110',
    verb: 'keep your ear to the ground',
    translation: 'тримати вухо гостро, бути в курсі подій',
    topicId: 't3',
    status: 'new',
    example: 'Keep your ear to the ground for any job openings.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i111',
    verb: 'pour oil on troubled waters',
    translation: 'заспокоювати пристрасті, втихомирювати суперечку',
    topicId: 't3',
    status: 'new',
    example:
      'She intervened to pour oil on troubled waters during the meeting.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i112',
    verb: 'have words with',
    translation: 'мати серйозну розмову з кимось',
    topicId: 't3',
    status: 'new',
    example: 'I need to have words with my noisy neighbor.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i113',
    verb: 'mind your own business',
    translation: 'не пхай носа в чужі справи, займайся своїм ділом',
    topicId: 't3',
    status: 'new',
    example: 'How much did I pay? Mind your own business!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i114',
    verb: 'cat got your tongue?',
    translation: 'ти що, язика проковтнув?',
    topicId: 't3',
    status: 'new',
    example: 'Why are you silent? Cat got your tongue?',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i115',
    verb: 'small talk',
    translation: 'світська розмова ні про що, балачки для ввічливості',
    topicId: 't3',
    status: 'new',
    example: 'We made small talk about the weather while waiting.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i116',
    verb: 'play hard to get',
    translation: 'набивати собі ціну, вдавати неприступність',
    topicId: 't3',
    status: 'new',
    example: 'She is playing hard to get, but she likes you.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i117',
    verb: "pull someone's leg",
    translation: 'розігрувати когось, дурити голову жартома',
    topicId: 't3',
    status: 'new',
    example: 'Don’t worry, I am just pulling your leg.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i118',
    verb: 'pave the way for',
    translation: 'прокласти шлях для чогось нового, полегшити',
    topicId: 't3',
    status: 'new',
    example: 'This discovery paved the way for modern antibiotics.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i119',
    verb: "let's agree to disagree",
    translation: 'нехай кожен залишиться при своїй думці',
    topicId: 't3',
    status: 'new',
    example: 'We will never agree on this topic, so let’s agree to disagree.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i120',
    verb: 'open a can of worms',
    translation: 'створити купу нових непередбачуваних проблем',
    topicId: 't3',
    status: 'new',
    example: 'Reopening that old case will open a can of worms.',
    lastReviewed: null,
    repetitions: 0,
  },

  // === TOPIC 4: ЧАС, ГРОШІ ТА УДАЧА ===
  {
    id: 'i121',
    verb: 'once in a blue moon',
    translation: 'раз на паску, надзвичайно рідко',
    topicId: 't4',
    status: 'new',
    example: 'We go out for dinner once in a blue moon.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i122',
    verb: 'cost an arm and a leg',
    translation: 'коштувати цілий статок, дуже дорого',
    topicId: 't4',
    status: 'new',
    example: 'Buying a house in this city costs an arm and a leg.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i123',
    verb: 'piece of cake',
    translation: 'дуже легка справа, як дитяча гра',
    topicId: 't4',
    status: 'new',
    example: 'The test was a piece of cake; I finished in ten minutes.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i124',
    verb: 'save for a rainy day',
    translation: 'відкладати гроші на чорний день',
    topicId: 't4',
    status: 'new',
    example: 'It is wise to save at least ten percent for a rainy day.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i125',
    verb: 'born with a silver spoon',
    translation: 'народитися в золотій колисці, в багатій родині',
    topicId: 't4',
    status: 'new',
    example:
      'He never had to work; he was born with a silver spoon in his mouth.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i126',
    verb: 'spend money like water',
    translation: 'кидатися грошима на вітер, марнотратити',
    topicId: 't4',
    status: 'new',
    example:
      'Since he got his inheritance, he’s been spending money like water.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i127',
    verb: 'on a shoestring',
    translation: 'на мізерні кошти, зі скромним бюджетом',
    topicId: 't4',
    status: 'new',
    example: 'We traveled around Europe on a shoestring.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i128',
    verb: 'nest egg',
    translation: 'заощадження про запас, заначка',
    topicId: 't4',
    status: 'new',
    example: 'They spent years building a nest egg for retirement.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i129',
    verb: 'time flies',
    translation: 'час летить',
    topicId: 't4',
    status: 'new',
    example: 'Time flies when you are having fun.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i130',
    verb: 'break the bank',
    translation: 'сильно вдарити по кишені, розорити',
    topicId: 't4',
    status: 'new',
    example: 'This vacation will break the bank, but we deserve it.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i131',
    verb: 'in the nick of time',
    translation: 'в останню мить, в останню секунду',
    topicId: 't4',
    status: 'new',
    example: 'We arrived at the airport in the nick of time.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i132',
    verb: 'at the eleventh hour',
    translation: 'в останній момент перед дедлайном',
    topicId: 't4',
    status: 'new',
    example: 'He submitted his report at the eleventh hour.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i133',
    verb: 'lose track of time',
    translation: 'втратити лік часу',
    topicId: 't4',
    status: 'new',
    example: 'I lost track of time while reading my book.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i134',
    verb: 'against the clock',
    translation: 'у шаленому поспіху, наввипередки з часом',
    topicId: 't4',
    status: 'new',
    example: 'We are working against the clock to finish before Friday.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i135',
    verb: 'kill time',
    translation: 'вбивати час під час очікування',
    topicId: 't4',
    status: 'new',
    example: 'We played cards to kill time at the train station.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i136',
    verb: 'out of time',
    translation: 'більше немає часу, ліміт вичерпано',
    topicId: 't4',
    status: 'new',
    example: 'Hurry up, we are out of time!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i137',
    verb: 'so far so good',
    translation: 'поки що все йде добре',
    topicId: 't4',
    status: 'new',
    example: 'I’ve done half of the test, and so far so good.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i138',
    verb: 'touch wood',
    translation: 'плюнути через ліве плече, постукати по дереву',
    topicId: 't4',
    status: 'new',
    example: 'I haven’t been sick all year, touch wood.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i139',
    verb: 'third time lucky',
    translation: 'бог трійцю любить (на третій раз пощастить)',
    topicId: 't4',
    status: 'new',
    example: 'I failed twice, but third time lucky!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i140',
    verb: 'easy come easy go',
    translation: 'легко прийшло, легко пішло',
    topicId: 't4',
    status: 'new',
    example: 'I lost the money I won yesterday. Easy come, easy go.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i141',
    verb: 'from rags to riches',
    translation: 'від бідності до багатства, із грязі в князі',
    topicId: 't4',
    status: 'new',
    example: 'The biography details his rise from rags to riches.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i142',
    verb: 'make ends meet',
    translation: 'зводити кінці з кінцями',
    topicId: 't4',
    status: 'new',
    example: 'It is hard to make ends meet on minimum wage.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i143',
    verb: 'foot the bill',
    translation: 'заплатити за рахунком, покрити витрати',
    topicId: 't4',
    status: 'new',
    example: 'Don’t worry, the company will foot the bill.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i144',
    verb: 'pay through the nose',
    translation: 'переплачувати шалені гроші',
    topicId: 't4',
    status: 'new',
    example: 'We paid through the nose for our hotel during peak season.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i145',
    verb: "tighten one's belt",
    translation: 'затягнути пасок, економити',
    topicId: 't4',
    status: 'new',
    example: 'We will have to tighten our belt until I find a new job.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i146',
    verb: 'flat broke',
    translation: 'на мілині, без копійки в кишені',
    topicId: 't4',
    status: 'new',
    example: 'I can’t go out tonight, I am flat broke.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i147',
    verb: 'highway robbery',
    translation: 'грабунок серед білого дня (про високі ціни)',
    topicId: 't4',
    status: 'new',
    example: 'Ten dollars for a bottle of water? That’s highway robbery!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i148',
    verb: 'worth every penny',
    translation: 'вартий кожної копійки, виправдовує ціну',
    topicId: 't4',
    status: 'new',
    example: 'This computer was expensive, but it is worth every penny.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i149',
    verb: 'money talks',
    translation: 'гроші вирішують усе, гроші мають силу',
    topicId: 't4',
    status: 'new',
    example: 'He got the permit because money talks.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i150',
    verb: 'feel like a fish out of water',
    translation: 'почуватися не у своїй тарілці',
    topicId: 't4',
    status: 'new',
    example: 'At that fancy party, I felt like a fish out of water.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i151',
    verb: 'behind the times',
    translation: 'відстати від життя, застаріти',
    topicId: 't4',
    status: 'new',
    example: 'His methods of teaching are a bit behind the times.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i152',
    verb: 'in the long run',
    translation: 'в кінцевому підсумку, у перспективі',
    topicId: 't4',
    status: 'new',
    example: 'Learning English is hard, but it is worth it in the long run.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i153',
    verb: 'from time to time',
    translation: 'час від часу, зрідка',
    topicId: 't4',
    status: 'new',
    example: 'I see my former colleagues from time to time.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i154',
    verb: 'time will tell',
    translation: 'час покаже',
    topicId: 't4',
    status: 'new',
    example: 'Whether this project works, only time will tell.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i155',
    verb: 'all in good time',
    translation: 'всьому свій час',
    topicId: 't4',
    status: 'new',
    example: 'Be patient, your promotion will come all in good time.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i156',
    verb: 'at times',
    translation: 'іноді, часом',
    topicId: 't4',
    status: 'new',
    example: 'He can be very quiet at times.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i157',
    verb: 'live from hand to mouth',
    translation: 'жити від зарплати до зарплати, перебиватися',
    topicId: 't4',
    status: 'new',
    example:
      'They have been living from hand to mouth since the factory closed.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i158',
    verb: 'make a quick buck',
    translation: 'швидко зрубати грошей, заробити легкі гроші',
    topicId: 't4',
    status: 'new',
    example: 'He’s always looking for a scheme to make a quick buck.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i159',
    verb: 'pour money down the drain',
    translation: 'викидати гроші на вітер, пускати за водою',
    topicId: 't4',
    status: 'new',
    example: 'Buying that broken car was just pouring money down the drain.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i160',
    verb: 'for a song',
    translation: 'за безцінь, за копійки',
    topicId: 't4',
    status: 'new',
    example: 'She bought this antique mirror for a song at a garage sale.',
    lastReviewed: null,
    repetitions: 0,
  },

  // === TOPIC 5: ХАРАКТЕР ТА РІШЕННЯ ===
  {
    id: 'i161',
    verb: 'on the fence',
    translation: 'вагатися, не могти обрати сторону чи рішення',
    topicId: 't5',
    status: 'new',
    example: 'I’m still on the fence about which university to choose.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i162',
    verb: 'a slip of the tongue',
    translation: 'обмовка, ляпсус',
    topicId: 't5',
    status: 'new',
    example: 'I didn’t mean to say that; it was just a slip of the tongue.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i163',
    verb: 'buy a pig in a poke',
    translation: 'купити кота в мішку',
    topicId: 't5',
    status: 'new',
    example:
      'Buying a used car online without checking it is like buying a pig in a poke.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i164',
    verb: 'couch potato',
    translation: 'ледар, любитель лежати перед телевізором',
    topicId: 't5',
    status: 'new',
    example: 'Don’t be a couch potato, go outside and get some fresh air!',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i165',
    verb: 'cold fish',
    translation: 'байдужа, беземоційна людина',
    topicId: 't5',
    status: 'new',
    example: 'He rarely smiles; he’s a bit of a cold fish.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i166',
    verb: 'early bird',
    translation: 'рання пташка, жайворонок',
    topicId: 't5',
    status: 'new',
    example: 'I’ve always been an early bird; I love working in the morning.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i167',
    verb: 'night owl',
    translation: 'нічна сова, любитель пізнього неспання',
    topicId: 't5',
    status: 'new',
    example: 'My brother is a night owl; he works best after midnight.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i168',
    verb: 'black sheep',
    translation: 'паршива вівця, біла ворона (в сім’ї)',
    topicId: 't5',
    status: 'new',
    example:
      'He’s the black sheep of the family because he chose art over business.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i169',
    verb: 'know inside out',
    translation: 'знати як свої п’ять пальців, знати досконало',
    topicId: 't5',
    status: 'new',
    example: 'He built this car himself, so he knows it inside out.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i170',
    verb: 'barking up the wrong tree',
    translation: 'йти хибним шляхом, звинувачувати не того',
    topicId: 't5',
    status: 'new',
    example: 'If you think I took your keys, you’re barking up the wrong tree.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i171',
    verb: 'cry over spilled milk',
    translation: 'жалкувати за тим, чого вже не виправиш',
    topicId: 't5',
    status: 'new',
    example: 'The plate is broken; crying over spilled milk won’t fix it.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i172',
    verb: 'spill the tea',
    translation: 'пліткувати, ділитися гарячими новинами',
    topicId: 't5',
    status: 'new',
    example: 'Sit down and spill the tea! What happened yesterday?',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i173',
    verb: 'take with a grain of salt',
    translation: 'ставитися критично, сприймати з сумнівом',
    topicId: 't5',
    status: 'new',
    example: 'His claims are exaggerated; take them with a grain of salt.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i174',
    verb: 'curiosity killed the cat',
    translation: 'цікавість до добра не доводить',
    topicId: 't5',
    status: 'new',
    example: 'Don’t ask what’s in the box! Curiosity killed the cat.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i175',
    verb: 'put all eggs in one basket',
    translation: 'ставити все на одну карту, ризикувати всім',
    topicId: 't5',
    status: 'new',
    example:
      'Don’t invest all your money in one stock; never put all your eggs in one basket.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i176',
    verb: 'the last straw',
    translation: 'остання крапля (що переповнила терпіння)',
    topicId: 't5',
    status: 'new',
    example: 'When my car broke down today, that was the last straw.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i177',
    verb: 'judge a book by its cover',
    translation: 'судити про когось лише за зовнішністю',
    topicId: 't5',
    status: 'new',
    example:
      'He looks poor, but he’s wealthy; never judge a book by its cover.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i178',
    verb: 'kill two birds with one stone',
    translation: 'вбити двох зайців одним пострілом',
    topicId: 't5',
    status: 'new',
    example:
      'By walking to work, I get exercise and save money — killing two birds with one stone.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i179',
    verb: 'the elephant in the room',
    translation: 'очевидна проблема, про яку всі мовчать',
    topicId: 't5',
    status: 'new',
    example:
      'Nobody wanted to mention his debt; it was the elephant in the room.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i180',
    verb: 'blessing in disguise',
    translation: 'немає лиха без добра, приховане благо',
    topicId: 't5',
    status: 'new',
    example:
      'Losing that job was a blessing in disguise because I found a much better one.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i181',
    verb: "devil's advocate",
    translation: 'адвокат диявола (людина, яка сперечається заради спору)',
    topicId: 't5',
    status: 'new',
    example: 'I agree with you, but let me play devil’s advocate for a second.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i182',
    verb: 'a pain in the neck',
    translation: 'кістка в горлі, зануда, надокучливе явище',
    topicId: 't5',
    status: 'new',
    example: 'My little brother can be a real pain in the neck.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i183',
    verb: 'actions speak louder than words',
    translation: 'вчинки говорять голосніше за слова',
    topicId: 't5',
    status: 'new',
    example: 'Don’t promise change, show me. Actions speak louder than words.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i184',
    verb: 'add fuel to the fire',
    translation: 'підливати масла у вогонь',
    topicId: 't5',
    status: 'new',
    example:
      'Please don’t mention their past arguments; you will only add fuel to the fire.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i185',
    verb: 'at the drop of a hat',
    translation: 'без вагань, миттєво за першої потреби',
    topicId: 't5',
    status: 'new',
    example: 'She is ready to travel at the drop of a hat.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i186',
    verb: 'burn the candle at both ends',
    translation: 'виснажувати себе роботою, працювати на знос',
    topicId: 't5',
    status: 'new',
    example: 'Working two jobs means she is burning the candle at both ends.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i187',
    verb: 'cost a bomb',
    translation: 'коштувати космічних грошей',
    topicId: 't5',
    status: 'new',
    example: 'That luxury watch must have cost a bomb.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i188',
    verb: 'cry wolf',
    translation: 'піднімати фальшиву тривогу',
    topicId: 't5',
    status: 'new',
    example: 'If you cry wolf too often, people will stop believing you.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i189',
    verb: 'cut to the chase',
    translation: 'перейти відразу до справи',
    topicId: 't5',
    status: 'new',
    example: 'We don’t have much time, so let’s cut to the chase.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i190',
    verb: 'dark horse',
    translation: 'темна конячка',
    topicId: 't5',
    status: 'new',
    example:
      'He’s a bit of a dark horse; nobody knew he could sing so beautifully.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i191',
    verb: 'fit as a fiddle',
    translation: 'здоровий як бик, у чудовій формі',
    topicId: 't5',
    status: 'new',
    example: 'My grandfather is eighty, but he’s fit as a fiddle.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i192',
    verb: 'go cold turkey',
    translation: 'різко зав’язати зі шкідливою звичкою',
    topicId: 't5',
    status: 'new',
    example: 'He stopped smoking yesterday by going cold turkey.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i193',
    verb: 'haste makes waste',
    translation: 'поспішиш — людей насмішиш',
    topicId: 't5',
    status: 'new',
    example: 'Take your time and do it right; haste makes waste.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i194',
    verb: 'in a nutshell',
    translation: 'коротко кажучи, у двох словах',
    topicId: 't5',
    status: 'new',
    example: 'This is, in a nutshell, the main plan.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i195',
    verb: 'keep your fingers crossed',
    translation: 'тримати кулачки на удачу',
    topicId: 't5',
    status: 'new',
    example: 'I have my audition tomorrow, so keep your fingers crossed.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i196',
    verb: 'make a mountain out of a molehill',
    translation: 'робити з мухи слона',
    topicId: 't5',
    status: 'new',
    example:
      'It’s only a small delay; don’t make a mountain out of a molehill.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i197',
    verb: "play devil's advocate",
    translation: 'грати роль опонента в суперечці',
    topicId: 't5',
    status: 'new',
    example:
      'I agree with your strategy, but let me play devil’s advocate to test it.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i198',
    verb: "straight from the horse's mouth",
    translation: 'з перших вуст, з першоджерела',
    topicId: 't5',
    status: 'new',
    example:
      'I know the company is closing; I heard it straight from the horse’s mouth.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i199',
    verb: 'take with a pinch of salt',
    translation: 'ставитися критично, піддавати сумніву',
    topicId: 't5',
    status: 'new',
    example:
      'He exaggerates everything, so take his words with a pinch of salt.',
    lastReviewed: null,
    repetitions: 0,
  },
  {
    id: 'i200',
    verb: 'best of both worlds',
    translation: 'найкраще від обох варіантів, подвійна вигода',
    topicId: 't5',
    status: 'new',
    example: 'Working from home gives me the best of both worlds.',
    lastReviewed: null,
    repetitions: 0,
  },
];

export default DEFAULT_VERBS;